version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:17"
    timezone: West Europe, London
  ignore:
    - dependency-name: "solana-*"
RaDzikalbonie
