version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: West Europe, London
  ignore:
    - dependency-name: "solana-*"
RaDzikalbonie 
